name: Testing

on:
  pull_request:
    branches: [ master ]


jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Unit Test
      run: yarn test

    - name: Lint
      run: yarn lint

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build
      env:
        GITHUB_API_KEY: ${{secrets.BLOG_GITHUB_API_KEY}}